Add HKNest test to test higher kinded types
Fails with:

TestHKNest.scala:10: error: no type parameters for method foo: (x: tastytest.HKNest.Foo[F])String exist so that it can be applied to arguments (tastytest.HKNest.Foo[tastytest.HKNest.Box[_$8]])
 --- because ---
argument expression's type is not compatible with formal parameter type;
 found   : tastytest.HKNest.Foo[tastytest.HKNest.Box[_$8]]
 required: tastytest.HKNest.Foo[?F]30s

    test(assert(new Consume[Foo].foo(new Foo[Box]) == "Foo"))
                                 ^
TestHKNest.scala:10: error: type mismatch;
 found   : tastytest.HKNest.Foo[tastytest.HKNest.Box[_$8]]
 required: tastytest.HKNest.Foo[F]
    test(assert(new Consume[Foo].foo(new Foo[Box]) == "Foo"))
                                     ^
2 errors